S3_BUCKET = "context-aware-misinformation-detection"
AWS_REGION = "us-east-1"
AWS_ACCESS_KEY_ID = "AKIAQD6M2IGEIQXVPO47"
AWS_SECRET_ACCESS_KEY = "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"

GROQ_API_KEY = "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"

TABLEAU_URL = ""